### PR TITLE
Protecting get_chem() against 'Divide by zero error' in fecond calculation

### LINKED ISSUE #116: Error in collected get_chem() output for specific data
Below problem was found when running the data collection part of a `calculate_ir()` example in PR #114.

For this specific case, the problem pops up when collecting "ZWA" data from 2023, not in the data before and after. It is also to be considered whether solving that still makes sense in the light of migration to the new datawarehouse.

```r
>   mydata <-
    get_locs(watina, area_codes = "ZWA") %>%
    get_chem(watina, "1/1/2019") %>%
    collect()
Error in `collect()`:
! Failed to collect lazy table.
Caused by error:
! nanodbc/nanodbc.cpp:3648: 00000
[Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Divide by zero error encountered. 
[Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Warning: Null value is eliminated by an aggregate or other SET operation. 
Run `rlang::last_trace()` to see where the error occurred.
Warning message:
In dbClearResult(res) : Result already cleared

>   get_locs(watina, area_codes = "ZWA") %>%
    get_chem(watina, "1/1/2023") |> collect()
Error in `collect()`:
! Failed to collect lazy table.
Caused by error:
! nanodbc/nanodbc.cpp:3648: 00000
[Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Divide by zero error encountered. 
[Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Warning: Null value is eliminated by an aggregate or other SET operation. 
Run `rlang::last_trace()` to see where the error occurred.
Warning message:
In dbClearResult(res) : Result already cleared

>   get_locs(watina, area_codes = "ZWA") %>%
    get_chem(watina, "1/1/2024") |> collect()
# A tibble: 139 × 10
   loc_code date       lab_project_id lab_sample_id chem_variable   value unit  below_loq   loq  elneutr
   <chr>    <date>     <chr>          <chr>         <chr>           <dbl> <chr> <lgl>     <dbl>    <dbl>
 1 ZWAP259  2025-05-07 0              42726         Mg             17.5   mg/l  FALSE       -99 0.000462
 2 ZWAP259  2025-05-07 0              42726         P-PO4           0.015 mg/l  TRUE        -99 0.000462
 3 ZWAP259  2025-05-07 0              42726         Al              0.225 mg/l  FALSE       -99 0.000462
 4 ZWAP259  2025-05-07 0              42726         Fe              0.05  mg/l  TRUE        -99 0.000462
 5 ZWAP259  2025-05-07 0              42726         CondL         384.    µS/cm FALSE       -99 0.000462
 6 ZWAP259  2025-05-07 0              42726         N-NO3          18.7   mg/l  FALSE       -99 0.000462
 7 ZWAP259  2025-05-07 0              42726         K              33.3   mg/l  FALSE       -99 0.000462
 8 ZWAP259  2025-05-07 0              42726         Mn              1.28  mg/l  FALSE       -99 0.000462
 9 ZWAP259  2025-05-07 0              42726         Ca              8.34  mg/l  FALSE       -99 0.000462
10 ZWAP259  2025-05-07 0              42726         CondF         398     µS/cm FALSE       -99 0.000462
# ℹ 129 more rows
# ℹ Use `print(n = ...)` to see more rows

>   get_locs(watina, area_codes = "ZWA") %>%
    get_chem(watina, "1/1/2019", "1/1/2022") |> collect()
# A tibble: 1,409 × 10
   loc_code date       lab_project_id lab_sample_id chem_variable   value unit  below_loq   loq elneutr
   <chr>    <date>     <chr>          <chr>         <chr>           <dbl> <chr> <lgl>     <dbl>   <dbl>
 1 ZWAP242  2019-02-27 0              40224         CondF         209     µS/cm FALSE       -99  0.0426
 2 ZWAP242  2019-02-27 0              40224         N-NO3           0.028 mg/l  FALSE       -99  0.0426
 3 ZWAP242  2019-02-27 0              40224         Mn              0.05  mg/l  TRUE        -99  0.0426
 4 ZWAP242  2019-02-27 0              40224         Al              0.05  mg/l  TRUE        -99  0.0426
 5 ZWAP242  2019-02-27 0              40224         N-NO2           0.015 mg/l  TRUE        -99  0.0426
 6 ZWAP242  2019-02-27 0              40224         N-NH4           0.02  mg/l  TRUE        -99  0.0426
 7 ZWAP242  2019-02-27 0              40224         Cl              4.64  mg/l  FALSE       -99  0.0426
 8 ZWAP242  2019-02-27 0              40224         P-PO4           0.015 mg/l  TRUE        -99  0.0426
 9 ZWAP242  2019-02-27 0              40224         K               0.15  mg/l  FALSE       -99  0.0426
10 ZWAP242  2019-02-27 0              40224         Fe              6.08  mg/l  FALSE       -99  0.0426
# ℹ 1,399 more rows
# ℹ Use `print(n = ...)` to see more rows
```

### PR DESCRIPTION
**Pull request by florisvdh**
This fixes #116 by implementing the proposals made in https://github.com/inbo/watina/issues/116#issuecomment-4154748031.

~It seems that @fredericpiesschaert already replaced the zero values in the database, as the problem has gone for "RAV" without warning when using either the code of this branch or from current `dev_nextrelease`.~ ==> no, I just didn't filter for the problematic locations. Solved below in https://github.com/inbo/watina/pull/122#issuecomment-4155424392.

Tell me @cecileherr @fredericpiesschaert if you wish to review / test, so that I wait before merging this PR.

### CODE REVIEW

**Comment by fredericpiesschaert** [comment]
I didn't replace anything yet...

**Comment by florisvdh** [comment]
> I didn't replace anything yet...

Ah, my bad: it was because I forgot to add `collect()` in some of the tests.

That means we should still be able to trigger the warning. :slightly_smiling_face:

**Comment by florisvdh** [comment]
No, the problem was not in doing `collect()`, but in getting the right RAV locations.

We now get the warning and a meaningful result at the same time:

``` r
library(dplyr, warn.conflicts = FALSE)
library(watina)
watina <- connect_watina()
all_locs_rav <- get_locs(
  con = watina,
  area_codes = "RAV",
  loc_type = c("P", "S", "R", "N", "W", "D", "L", "B")
)
all_locs_rav %>% 
  get_chem(watina, "1/1/2017") %>% 
  count()
#> Warning in get_chem(., watina, "1/1/2017"): Zeroes for 'CondL' (lab
#> conductivity) detected. These rows will be ignored in calculating the iron /
#> conductivity ratio for the `fecond` condition.
#> # Source:   SQL [?? x 1]
#> # Database: Microsoft SQL Server
#>         n
#>   <int64>
#> 1    1682
```

<sup>Created on 2026-03-30 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">

<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.5.3 (2026-03-11)
#>  os       Linux Mint 22.3
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language nl_BE:nl
#>  collate  nl_BE.UTF-8
#>  ctype    nl_BE.UTF-8
#>  tz       Europe/Brussels
#>  date     2026-03-30
#>  pandoc   3.6.3 @ /usr/lib/rstudio/resources/app/bin/quarto/bin/tools/x86_64/ (via rmarkdown)
#>  quarto   1.8.25 @ /usr/lib/rstudio/resources/app/bin/quarto/bin/quarto
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date (UTC) lib source
#>  assertthat    0.2.1      2019-03-21 [1] RSPM (R 4.4.0)
#>  bit           4.6.0      2025-03-06 [1] RSPM (R 4.4.0)
#>  bit64         4.6.0-1    2025-01-16 [1] RSPM (R 4.4.0)
#>  blob          1.3.0      2026-01-14 [1] CRAN (R 4.5.2)
#>  cli           3.6.5      2025-04-23 [1] RSPM (R 4.4.0)
#>  DBI           1.3.0      2026-02-25 [1] CRAN (R 4.5.2)
#>  dbplyr        2.5.2      2026-02-13 [3] CRAN (R 4.5.2)
#>  digest        0.6.39     2025-11-19 [1] CRAN (R 4.5.2)
#>  dplyr       * 1.2.0      2026-02-03 [1] CRAN (R 4.5.2)
#>  evaluate      1.0.5      2025-08-27 [1] RSPM (R 4.5.0)
#>  fastmap       1.2.0      2024-05-15 [1] RSPM (R 4.4.2)
#>  fs            2.0.1      2026-03-24 [1] CRAN (R 4.5.3)
#>  generics      0.1.4      2025-05-09 [1] RSPM (R 4.5.0)
#>  glue          1.8.0      2024-09-30 [1] RSPM (R 4.4.2)
#>  hms           1.1.4      2025-10-17 [1] RSPM (R 4.5.0)
#>  htmltools     0.5.9      2025-12-04 [1] CRAN (R 4.5.2)
#>  inbodb        0.0.7      2025-09-08 [1] https://inbo.r-universe.dev (R 4.5.1)
#>  knitr         1.51       2025-12-20 [1] CRAN (R 4.5.2)
#>  lifecycle     1.0.5      2026-01-08 [1] CRAN (R 4.5.2)
#>  lubridate     1.9.5      2026-02-04 [1] CRAN (R 4.5.2)
#>  magrittr      2.0.4      2025-09-12 [1] RSPM (R 4.5.0)
#>  odbc          1.6.4.1    2025-12-24 [1] CRAN (R 4.5.2)
#>  otel          0.2.0      2025-08-29 [1] RSPM (R 4.5.0)
#>  pillar        1.11.1     2025-09-17 [1] RSPM (R 4.5.0)
#>  pkgconfig     2.0.3      2019-09-22 [1] RSPM (R 4.4.0)
#>  purrr         1.2.1      2026-01-09 [1] CRAN (R 4.5.2)
#>  R6            2.6.1      2025-02-15 [1] RSPM (R 4.4.0)
#>  Rcpp          1.1.1      2026-01-10 [1] CRAN (R 4.5.2)
#>  reprex        2.1.1      2024-07-06 [3] RSPM (R 4.4.0)
#>  rlang         1.1.7      2026-01-09 [1] CRAN (R 4.5.2)
#>  rmarkdown     2.31       2026-03-26 [1] CRAN (R 4.5.3)
#>  rstudioapi    0.18.0     2026-01-16 [1] CRAN (R 4.5.2)
#>  sessioninfo   1.2.3      2025-02-05 [1] RSPM (R 4.4.0)
#>  stringi       1.8.7      2025-03-27 [1] RSPM (R 4.4.0)
#>  stringr       1.6.0      2025-11-04 [1] RSPM (R 4.5.0)
#>  tibble        3.3.1      2026-01-11 [1] CRAN (R 4.5.2)
#>  tidyr         1.3.2      2025-12-19 [1] CRAN (R 4.5.2)
#>  tidyselect    1.2.1      2024-03-11 [1] RSPM (R 4.4.0)
#>  timechange    0.4.0      2026-01-29 [1] CRAN (R 4.5.2)
#>  vctrs         0.7.2      2026-03-21 [1] CRAN (R 4.5.3)
#>  watina      * 0.4.2.9000 2026-03-30 [1] Github (inbo/watina@b5f4e80)
#>  withr         3.0.2      2024-10-28 [1] RSPM (R 4.4.0)
#>  xfun          0.57       2026-03-20 [1] CRAN (R 4.5.3)
#>  yaml          2.3.12     2025-12-10 [1] CRAN (R 4.5.2)
#> 
#>  [1] /home/floris/lib/R/library
#>  [2] /usr/local/lib/R/site-library
#>  [3] /usr/lib/R/site-library
#>  [4] /usr/lib/R/library
#>  * ── Packages attached to the search path.
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by cecileherr** [comment]
It might not matter here but FYI: the DWH00 had not been updated since begin March. Jo and I noticed it on Mar 27th and he reactivated the synchronization with the production db. 
So if there have been updates in the last 3 weeks, they will only have appeared very recently in the DWH00.

**Comment by cecileherr** [comment]
> Tell me @cecileherr @fredericpiesschaert if you wish to review / test, so that I wait before merging this PR.

Yes please, I want to try it :-)

File: R/get.R [hunk 1]
```diff
@@ -1418,38 +1424,26 @@ get_chem <- function(locs,
...
-        .data$Datum <= enddate
+        .data$ChemVarCode == "CondL",
+        !is.na(.data$MeetwaardeMEQ)
       ) %>%
+      pull(.data$MeetwaardeMEQ) == 0
+    )) {
+      warning(
+        "Zeroes for 'CondL' (lab conductivity) detected. ",
+        "These rows will be ignored in calculating the iron / conductivity ",
+        "ratio for the `fecond` condition."
```
Comment (cecileherr) [inline R/get.R]: nice to have a clear warning! Maybe replace 'fecond' by the official name of the argument:  "en_fecond_threshold"

Comment (florisvdh) [reply R/get.R]: Done in 560c485.

**Comment by fredericpiesschaert** [comment]
if it's approved by Cecile, all good for me

**Review by cecileherr — APPROVED** [review]
Nice! Thank you for resolving the issue so quickly!

**Comment by florisvdh** [comment]
Thanks for reviewing!
